export const FETCH_MOVIES = '@@app/FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = '@@app/FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = '@@app/FETCH_MOVIES_FAILED';

export const ADD_TO_FAVORITES = '@@app/ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = '@@app/REMOVE_FROM_FAVORITES';
